#!/usr/bin/env bash
#bad luck for the 4th loop iteration
# good luck for the 8th loop iteration
# Best School for the other iterations
m=1
while [ $m -le 10 ]
do
	if [ $m -eq 4 ]; then
		echo "bad luck"
	elif [ $m -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	m=$((m+1))
done
