#!/usr/bin/env bash
# Fizzbuzz

for number in {1..100}
do
if (( number % 5 == 0 && number % 3 ==0 ))
then
echo "FizzBuzz"
elif ((number % 3 == 0))
then
echo "Fizz"
elif ((number % 5 == 0))
then
echo "Buzz"
else
echo "$number"
fi
done
