#!/usr/bin/env bash
# Telling a story based on the contents of the "/etc/passwd" file.

while IFS=':' read -r username password uid gid info home shell; do
  echo "The username $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "For more info about the user here: $info"
done < "/etc/passwd"
